### PR TITLE
Gray Plushie

### PR DESCRIPTION
**Pull request by Tox3ct**
piskun unauthorized being now in the plushy pool. special digestion turned off because i think it's funny to eat them but if that's bad then yeah

https://github.com/user-attachments/assets/ae9d186e-95f1-44bb-8052-f231de75e5e5

**Changelog**

:cl:
- add: Added gray plushie. thui love keb piskun plushie

### CODE REVIEW

**Comment by Tox3ct** [comment]
plushie_graybig

piskun headass i hope everyone hurts him

**Comment by icecreamjones** [comment]
kicking it out an airlock just on principle. <3

**Comment by Tox3ct** [comment]
formally apologizing for the absolutely nightmarish amount of commits but everything should be good now!

**Comment by Pinkbat5** [comment]
REALLY GOOD

**Pull request merged**
