### PR TITLE
Coloring Changes

### PR DESCRIPTION
**Pull request by honeyed-lemons**
:cl:
- tweak: Updated Hydroponics Jumpsuit, Jumpskirt, and backpack colors.
- tweak: Updated Engineering Jumpsuit and Jumpskirt colors.

### CODE REVIEW

**Review by hivehum — CHANGES_REQUESTED** [review]
do me a favoeur and edit the respective meta.jsons to indicate that you have edited these sprites

**Comment by honeyed-lemons** [comment]
donezo :)

**Comment by hivehum** [comment]
you missed backpacks/hydroponics.rsi and mistakenly edited duffels/duffel.rsi

**Review by hivehum — APPROVED** [review]
thumps up

**Pull request merged**
