### PR TITLE
Fix Space Debris Spawning Empty

### PR DESCRIPTION
**Pull request by formlessnameless**
Porting a one line change from upstream. 

:cl:
- fix: Space debris is no longer a barren wasteland

### CODE REVIEW

**Comment by formlessnameless** [comment]
i am using my executive rights to Just Fucking Merge This actually

**Comment by Darkmajia** [comment]
whatever happened to democracy

**Comment by kipdotnet** [comment]
fucking insane that a one line fix took two weeks. it isnt even merged upstream I dont think

**Comment by formlessnameless** [comment]
i am declaring martial law to give salvagers their trash back. also this was merged into master upstream like a day or so ago lol.

**Pull request merged**
