### PR TITLE
Revenants now unembed projectiles upon becoming uncorporeal

### LINKED ISSUE #1169: Animated items embedded in revenants continue to attack even after the revenant dematerializes.
## Description
If an item gets embedded in a revenant, and then it animates the item, the item will continue to attack even after the revenant disappears.

**Reproduction**
1. Throw skewer at manifested revenant.
2. Revenant animates skewer
3. Revenant disappears
4. Skewer continues attacking even though it is now invisible.

### PR DESCRIPTION
**Pull request by TGRCdev**
When revenants disappear, any embedded projectiles will now drop out of them. Fixes #1169.

### CODE REVIEW

**Comment by Darkmajia** [comment]
this will probably conflict with #1157 :pensive:

**Comment by TGRCdev** [comment]
:withered:

**Comment by Darkmajia** [comment]
SORRY

**Comment by TGRCdev** [comment]
Its funny because EE did the same thing I did, which was adding a method to unembed any embedded entity. So this is cool actually and I can fix this

**Review by Darkmajia — APPROVED** [review]

**Pull request merged**
