### PR TITLE
slime gasps

### PR DESCRIPTION
**Pull request by hivehum**
these sound a little scuffed ingame imo but its chill

**Changelog**

:cl: harpy & credey
- add: Slimes now have unique gasps and deathgasps.

### CODE REVIEW

**Comment by TGRCdev** [comment]
Are they mono?

**Comment by hivehum** [comment]
oh my stupid ass didnt even check

**Comment by hivehum** [comment]
yes they're mono

**Comment by irismessage** [comment]
damn when are we gonna get some sounds that are poly

**Comment by hivehum** [comment]
harpy also sent me a new batch of files that are hopefully louder ingame so that has been put in this PR

**Review by TGRCdev — APPROVED** [review]

**Pull request merged**
