### PR TITLE
Different Entities Have Different Entry Times

### PR DESCRIPTION
**Pull request by formlessnameless**
Obviously subject to change if any of them feel busted.

:cl:
- tweak: Vent crawlers now have different vent entry times based on their size.

### CODE REVIEW

**Comment by hivehum** [comment]
WOOOO YEAH PR 1000!!!!!

**Comment by formlessnameless** [comment]
how the fuck did we get here

**Comment by kipdotnet** [comment]
the power of incredible violence

**Comment by sususuyo** [comment]
give it up for 1000!!!!!

**Comment by YesOfCourse0** [comment]
1000, damn. it doesnt feel real lol

**Comment by Darkmajia** [comment]
could this be based on density or something rather than having manual values set? i guess manual values are fine too

**Comment by formlessnameless** [comment]
it could, but it would need a system rewrite. i'm down to do it but this was already possible with the current structure, so I just used that.

**Pull request merged**
