### PR TITLE
new brigmed hat, and spawn with EMT belt

### PR DESCRIPTION
**Pull request by Sha-Seng**
:cl:
- add: Brigmedic Cap is now obtainable at spawn or from the secdrobe for ballcap enjoyers
- tweak: Brigmedics now spawn with the paramed belt since it doesn't look horrible with their uniform
- tweak: MedSec HUD no longer requires a radio to craft since it has no communication functionality
- tweak: MedSec HUD lens opacity increased so odd skin/eyes don't ruin the good look

### CODE REVIEW

**Comment by hivehum** [comment]
maybe we should not make an item that has every buff a pair of glasses possibly can have

**Comment by mqole** [comment]
also not a huge fan of this pr, i think that the medsec hud is interesting enough as an item already. adding any more buffs to it (especially flash prot, which is always huge) is just unnecessary, especially when the secglasses are also an option for brigmed. if a brigmed really wants flash protection make them have to sacrifice an inventory slot for it. thats more interesting

**Comment by hivehum** [comment]
plenty of other glasses dont have flash protection (engineering goggles, chemical analyzers, beer goggles, etc) so i dont necessarily think "it covers both eyes" is a good justification for giving it flash protection either

i do mostly play brigmed when i play sec and im not really interested in having such easy access to the security overlay / having no downside or work required to obtain access to both sec and med overlays. i think this might encourage brigmed to play surrogate secoff which i am not a huge fan of

**Comment by hivehum** [comment]
okay. im a brigmed player and i dont read the security thread. i have given my input. having to juggle resources is cool and good. add sunglasses to the craft requirement if you want to give medsec flash protection

**Comment by hivehum** [comment]
yeah im saying keep it craftable but make it take sunglasses instead of a radio. still a difficult craft and you are exchanging one form of flash protection with another

**Comment by DinnerCalzone** [comment]
I feel like making the extant MedSec hud stronger and more restricted while making a new entity that works the same as the old one is over-engineering a buff to Brigmedic. I think that it's an interesting weakness having to trade flash immunity for a medical hud. Something like this would be better as a tech research.

**Comment by Pinkbat5** [comment]
I don't personally expect brigmeds treating themselves as "secoff+" to increase with the addition of flash protection. If they want to play that way, they're going to use the most popular detainment tools (disabler, baton and cuffs) that are already freely available and easy to use. Flashes are highly useful but often underappreciated, and protection would only make arrests slightly easier to execute.
That said, the missing flash protection doesn't really bother me as brigmed, though I haven't played recently so take that with a grain of salt. I kinda like the idea of brigmeds being slightly more vulnerable than the regular officer. But I'm not against it! If we're going to have these implemented, making them craftable instead of roundstart seems like the best approach. _Maybe_ a tech research if there is a pre-existing research tier that makes sense for it.
Maybe the non-flash huds could be roundstart instead, as a QOL change. Having to craft them isn't the end of the world, but it's kind of a pain in the ass, especially with radios being part of the recipe for some reason. That was stupid, thanks for removing it.

**Comment by hivehum** [comment]
the secoff+ comment is regarding having brigmeds start with a secmed hud and thus not having to choose between sechud (seeing wanted status/job icons/etc) and medhud (seeing health bars). the flash protection is its separate issue.

**Comment by hivehum** [comment]
ive only bothered making a secmed hud once on my brigmed and i really enjoyed how labor intensive it was. i had a lot of cross departmental interaction trying to get the capacitors and radio and developed a rapport with characters i had never interacted w before. i realize that i play hotwheels as a freak and im also very hardline "this is a doctor for security/prisoners and not a security officer" but i dont really see the desire for having a sechud as a brigmed. and regarding the flash protection i dont think ive ever gotten hit with a flash during a brigmed shift. its not like a top ten job for me but ive definitely done 4 or 5 shifts as one

**Comment by Pinkbat5** [comment]
Playing brigmedic without the medsec hud is completely crazy to me. (Not in a bad way, just dramatically different from how I play). As far as I'm concerned the medsec hud is the iconic Brigmedic Tool. It's as pivotbash said, they ought to have at least one unique tool and the hud seems specifically designed for the job.
I'm personally against nerfing what shows on the hud, it defeats the whole purpose of the thing. I'm also against making it exclusive to brigmedic entirely, unless only the flash-protection version is exclusive. CMO deserves the occasional blue alert pink-lensed treat.

**Review by hivehum — APPROVED** [review]
how we have forgotten those distant days where security and medical got in ever-escalating conflicts because the CMO wanted a medsec hud and security disagreed. now we all hold hands and sing kumbaya and celebrate world peace

wrt the "brigmed deserves one toy as a treat" situation, i think that the nerfs to the brigmed hardsuit should be rolled back. im also personally fine with giving the medsec hud flash protection if the recipe includes a pair of sunglasses because that maintains the resource scarcity regarding items with flash protection (as well as items with med/sec overlays since those remain part of the recipe). however these are both issues for a different pull request

**Comment by Pinkbat5** [comment]
I am actually planning to try to rebalance the brigmedic hardsuit! But you're right, not relevant to this PR

**Comment by Pivotbash** [comment]
since this pr was changed to just add a belt and hat, a second pr should be made to specifically talk about adding a flash proof and non-flash proof version of the glasses and it can be discussed there

**Review by formlessnameless — APPROVED** [review]

**Pull request merged**
