### PR TITLE
couple new tracks added to the armed nuke rotation

### PR DESCRIPTION
**Pull request by hivehum**
i dont need to suggest new music. i can just add it myself.

black tar SHOULD be okay copyright wise b/c youtube doesnt flag it but if the streamers have problems let me know

**Changelog**

:cl: hivehum
- add: Added two new songs that can play when the nuke is armed.

### CODE REVIEW

**Comment by hivehum** [comment]
WHAT DO YOU FUCKING MEAN IT HAS TO BE A URL. WHATEVER

**Comment by sususuyo** [comment]
you know i probably should have checked to see if you did this already before doing my addition. whoops!

**Comment by hivehum** [comment]
fix the attributions on your pr and ill close this one smile

**Comment by sususuyo** [comment]
yep all good now!

**Pull request closed without merging**
