### PR TITLE
Yet Another Resprite Bundle

### PR DESCRIPTION
**Pull request by AftrLite**
It's time for another giant pile of resprites yeah yeah here we go

- Medkits (All of 'em)
- Conveyors
- Computers
- The Maintenance Drone
- Bruise Pack
- Blood Pack
- Ointment
- Office Chairs
- The Nuclear Bomb (Including seasonal variants)
- Seclite
- Flashlight
- Wirecutters
- Screwdriver
- Drill
- Gas Analyzer
- Multitool
- Geiger Counter
- Appraisal Tool
- Mass Scanner
- RCD
- Comfy Chairs
- SMES

**Changelog**
:cl:
- tweak: Ongoing respriting efforts. Keep an eye out!
- fix: Fixed the InHands for Chaplain's Null Rod quiver's arrow.

### CODE REVIEW

**Comment by crocodilecarousel** [comment]
silhouette of the nuke is less readable at a glance. considering this is an object that is very important to be able to see easily, i recommend a less square shape.

gas analyzer looks very similar to the geiger counter. consider a different color. orange would maybe be good since thats another engineering color?

making brute packs and ointment sprites that big is going to make the medbay look more cluttered. completely vertical ointment sprite might be less readable as what it is at a glance. its giving toothpaste.

**Comment by hivehum** [comment]
piping in to say that I agree with cc's concerns regarding the nuke & also it feels kind of rude to respond to criticism with "well nobody else said this so I'm not going to change it". you are an extremely skilled sprite artist but you display a resistance to feedback that on multiple occasions has alienated people from wanting to respond to your resprite efforts

**Comment by hivehum** [comment]
also specifically regarding the nuke there are at least two seasonal resprites of it (present nuke and pride flag nuke) that I do not see here. I'm trapped on mobile for the foreseeable future so this could be github mobile ui fucking with me but do you intend to also resprite those assets?

**Comment by honeyed-lemons** [comment]
Personally I agree with all the concerns, I think the nuke texture would be more recognizable if it kept the hazard logo, and the color was darkened

**Comment by Pinkbat5** [comment]
I have to agree, the new nuke sprite is beautiful but lacks the original's cartoonish charm. I also do think the medical topicals are pretty, but a little too large. They don't need detail as much as they need simplicity and recognizability. I recall the sprite sheet you showed me had alternate topical sprites that were visually similar to the originals (ex. The ointment was diagonal instead of vertical, and still had a cross on it). I preferred those the most.
It's worth considering that saying something negative about technically impressive, high effort artwork is difficult to do. Especially if there's a LOT of changes coming from one person that is visibly putting in a very high amount of effort. It feels bad to be repeatedly negative towards that effort, even if the intent is to criticize constructively. If you want truly honest opinions you need to compensate for this trend and seek people's negative feedback and concerns as much as you can, without judgement or frustration. Absence of feedback does not mean the concerns are not there.

**Comment by crocodilecarousel** [comment]
> Changing the size of any given sprite will not make medbay more cluttered. People haphazardly scattering objects about is what makes rooms look cluttered. The only way to measurably increase the detail of item icons is by increasing their size, as all assets are baseline 32x32 pixels. I could make the icon one or two bandaids instead, but a brute "pack" implies it's a pack of them.

clutter

and things get haphazardly scattered in medbay frequently, as someone with several hundred hours in this department i know how things tend to be organized and where they end up over the course of a round. perhaps we can consider that the visual clarity and practicality of a smaller sprite is more important than increased detail, as it is not important for these items to stand out and it serves the gameplay better when two bruise packs do not obscure the entire tile beneath them. making them so large could be considered a balance issue as well considering how easy it is for them to hide anything under them.

**Review by Darkmajia — APPROVED** [review]

**Pull request merged**
