### PR TITLE
The juice that lets you see ghosts

### PR DESCRIPTION
**Pull request by Saeko-44**
**Changelog**

:cl:
- add: Medium, a new chemical that allows one to see ghosts

### CODE REVIEW

**Comment by sususuyo** [comment]
do you just see ghosts for the rest of the shift or is it temporary? out of curiosity

**Comment by Darkmajia** [comment]
this is a pretty attainable recipe for an effect that should be insanely limited. like, this is a wizard spell for one person. at the very least, it should be a more difficult recipe, it should have a threshold for the reagent to take effect, and it should only last for as long as the reagent lasts. though to be honest, i don't really know how to feel about these kinds of chemicals in general

**Comment by hivehum** [comment]
i dont feel strongly about this (i was half-heartedly working on something similar (making 100u mindbreaker let you see ghosts)) but i will say i dont think its wise to try and balance against wizard spells given that they arent fully implemented yet

**Comment by widgetbeck** [comment]
> drinking 0.5u of this seems to give you the effect forever (but i'm not sure if effects granted by reagents like this wear off after they finish metabolising)

yeah I think this reagent is fine as long as we can either 1) have the effect wear off pretty quickly over time proportional to dosage, or 2) have an extremely high metabolism requirement 
this effect is powerful enough that in my opinion it should be both hard to obtain and generally only accessible to one person. if you see a shitload of ghosts following someone around they're probably an antag

**Comment by Saeko-44** [comment]
Alright yall were concerned with the infinite duration so I fixed that

Now it works like polymorphing from weh juice or robust harvest ; when above 20u of the stuff is in your system, you unlock medium powers for a set duration (5 minutes)

**Review by widgetbeck — APPROVED** [review]

**Pull request merged**
