### PR TITLE
Random Unrevivable is now checked each defib

### PR DESCRIPTION
**Pull request by honeyed-lemons**
:cl:
- tweak: Random Unrevivable is checked after each defib, instead of roundstart.

### CODE REVIEW

**Comment by Darkmajia** [comment]
we simply cannot get enough of dnr. i don't have much of an opinion on this so i would appreciate it if dnr fans could put some thumbs up or down on whether this is preferred or not

**Comment by hivehum** [comment]
i believe this specific implementation of random unrevivable is preferred by DNR fans (i know stony has described it as their ideal to me quite a few times but iirc landshark also really wanted this) so consider this my thumbs up by proxy

**Comment by mqole** [comment]
just checking- does this continue rolling after unrevivable is rolled once? or once unrevivable is rolled the first time, does it stick for future defibs? (making sure we have a preventative measure for defib scumming)

**Comment by hivehum** [comment]
this rolls every single time the defibrillator is used on someone with the trait

**Comment by honeyed-lemons** [comment]
yes but if it fails, they cant be revived ever

**Review by hivehum — APPROVED** [review]
WE HAVE TO RUN AND MERGE THIS BEFORE THE NEXT UPSTREAM MERGE

**Pull request merged**
