### PR TITLE
Hypereutactic Blade

### PR DESCRIPTION
**Pull request by hivehum**
pring the [insane fuckoff laser greatsword from upstream](https://github.com/space-wizards/space-station-14/pull/32414) because i suspect it will not be merged. but it rules. it's so cool. i can't resist her

https://github.com/user-attachments/assets/52dab06e-9ef6-4768-b708-80b008fb7865

i lowered it to 75% reflect also because that seems a little absurd
the hand sprites look kind of bad but im not super familiar with how that works and this is just a straight mirror of that pr. i can come back and tweak it if its a problem

**Changelog**
:cl:
- add: Added the Hypereutactic Blade.

### CODE REVIEW

**Comment by Darkmajia** [comment]
this thing is really cool but it is an absolute nightmare to actually put in the uplink. i'd love it as an admin treat

**Comment by hivehum** [comment]
i just need ONE war ops round where they kit out in jugg suit dswords. please. ill fix it after

**Comment by Darkmajia** [comment]
ok. ok you can have this

**Comment by Darkmajia** [comment]
please move the contents of this pr to the _Impstation folder and i will give you the cool sword

**Comment by hivehum** [comment]
are you sure? i opted to not put it in _impstation because it's mirroring an upstream pr, and this would cause headaches if upstream did end up merging this. also i feel like putting it in our fork folder is misleading attribution-wise

**Comment by Darkmajia** [comment]
that's true, i suppose this is just an upstream pr. i doubt it'll go through but you're right about attribution

**Review by TGRCdev — APPROVED** [review]

**Pull request merged**
