### PR TITLE
Minor jukebox tweaks

### PR DESCRIPTION
**Pull request by TGRCdev**
**Changelog**

:cl: TGRCDev
- add: New volume slider for jukebox music

### CODE REVIEW

**Comment by hivehum** [comment]
hi please dont look at what this does and just merge it ty

**Comment by FlippenPage** [comment]
Hi please merge this and DO NOT fucking look at the changes thank youuu !!!! <3

**Comment by formlessnameless** [comment]
Making this a draft for now until the penance of the jukebox volume slider is complete

**Comment by TGRCdev** [comment]
This PR should be ready to merge following another PR in the upstream RobustToolbox repo.

**Pull request closed without merging**
