### PR TITLE
Space Wind

### PR DESCRIPTION
**Pull request by AirFryerBuyOneGetOneFree**
Add Space Wind! This is ported from Goobstation.

https://github.com/user-attachments/assets/cdf9ed23-ca77-47e9-b426-0aa240983118

**Changelog**

:cl:
- add: Added Space Wind!

### CODE REVIEW

**Comment by hivehum** [comment]
a29

**Comment by mqole** [comment]
it was mentioned somewhere but got lost so i'll throw in that this should probably be tested/implemented with consideration given to how space wind affects players with 3 digit ping (this post was made by the australian community)

**Comment by AirFryerBuyOneGetOneFree** [comment]
Yea I tested it at 600ms of ping and reeled in the humanoid throw multiplier Cvar. I posted a bunch of tests I did in dev chat, looks alright? Again, I recommend having a pr ready to simply turn space wind off in the Cvar if we do merge this, in case it doesn't work out in a real world server test.

**Review by TGRCdev — APPROVED** [review]

**Comment by TGRCdev** [comment]
If it's a CVar then I believe an admin can disable it in-game, as well as in the config file of the server.

**Pull request merged**
