### PR TITLE
medsec hud takes sunglasses and also will be less picky about capacitors

### PR DESCRIPTION
**Pull request by hivehum**
really easy fix that took me like 45 minutes to reverse engineer lmfao. holy shit construction is stupid

SS14 Loader_GQGA6OKJ8K

**Changelog**
:cl:
- tweak: The medsec hud now takes sunglasses to craft, instead of security glasses.

### CODE REVIEW

**Comment by hivehum** [comment]
SHUT THE FUCK UP ABOUT SOUP???

**Comment by Darkmajia** [comment]
oh god

**Comment by Darkmajia** [comment]
oh there IS a dupe soup. only now can i see it with github search

**Comment by formlessnameless** [comment]
there are no longer 2 soups. i am rerunning the thing

**Comment by formlessnameless** [comment]
IT'S STILL FAILING ON SOUP

**Comment by formlessnameless** [comment]
fuck it im going to approve and merge it

**Review by formlessnameless — APPROVED** [review]

**Comment by Darkmajia** [comment]
im sorry for soup

**Pull request merged**
