### PR TITLE
Shotgun Beanbag Rework

### PR DESCRIPTION
**Pull request by DinnerCalzone**
There has been some discussion around beanbag rounds being used as a non-lethal alternative to disablers, particularly with the addition of beanbag shotguns. Concerns have been raised over their brutality and real-world parallels with police violence. This PR renames beanbags to stun slugs, nerfs their damage to 7.5 per shot, and changes their damage type to shock, so they will not cause entities to bleed. These changes should hopefully allow security more non-lethal options while alleviating some discomfort around their use. All of these changes have been made to base game entities without renaming any of their IDs, so this should not require any changes in maps or other entities to function. This PR also pairs with #760 .

Additionally, since beanbag rounds could previously kill mice in one shot, mice have been given 40% shock vulnerability so this change will not impact bartenders as much. 

**Changelog**

:cl:
- tweak: Shotgun beanbags have been reworked into stun slugs. These do 7.5 shock and 40 stamina damage compared to beanbags' 10 blunt and 40 stamina damage, so being shot by them will not cause you to bleed. Note: insulated gloves will not make you immune to these!
- tweak: Gave mice 40% shock vulnerability so they can still be one-shot by the bartender's shotgun. (Their little hearts can't take the voltage.)

### CODE REVIEW

**Comment by hivehum** [comment]
wrt balance concerns, shock damage is harder to heal than blunt (and burn, for that matter), so i guess keep that in mind

**Comment by DinnerCalzone** [comment]
> wrt balance concerns, shock damage is harder to heal than blunt (and burn, for that matter), so i guess keep that in mind

I think you might have shock mixed up with something else. Shock is a type of burn damage and all common treatments of burn damage (ointment, kelotane, dermaline, tricordazine) all heal shock as much as they heal heat.

**Comment by kipdotnet** [comment]
really glad for this. felt a bit bad turning someone into a bloody mess as a stamina damage method lol

**Comment by Pinkbat5** [comment]
Will the shots still work on rat king servants, or does the mouse change affect them too?

**Comment by DinnerCalzone** [comment]
> Will the shots still work on rat king servants, or does the mouse change affect them too?

Rat Servants don't use mice as a parent entity, so this change would not affect them in its current state. Rat servants go crit at 15 damage, so this change would change make it so it would take 3 shots to crit them instead of 2. I'm hesitant to give them a shock weakness, even if shock is a relatively uncommon damage type, as I wouldn't want to directly affect antag balance with this. I suppose I could nudge up the damage up to 7.5 though.

**Review by starlighthowls — APPROVED** [review]

**Pull request merged**
