### PR TITLE
Add the Ability to Tie Jumpsuit Jackets around Waist

### PR DESCRIPTION
**Pull request by AirFryerBuyOneGetOneFree**
372208276-d5a466f8-f10b-4e3e-be12-ec05942271ad
372208281-10c46f9a-2759-427d-bba9-e7b23cd760bb

**Changelog**

:cl:Pinkbat5, AirFryerBuyOneGetOneFree
- add: You can now tie jumpsuits around your waist, slut style.

### CODE REVIEW

**Comment by formlessnameless** [comment]
Conflicts because of ninja changes looks like, also going to wait and merge this with the marking updates for shirts and stuff so people can actually decide how naked they want to be.

**Comment by Pinkbat5** [comment]
could you add my username to the changelog? >:)
also we can remove the ninja changes for now, I'll need to make a new sprite to reflect the new ninja sprite anyway

**Comment by formlessnameless** [comment]
The conflict is a single line having to do with attributions, it should be fine. If I understand how this works correctly I think it will just revert to the old sprite style when folded once this gets merged, and then you can update it at your leisure. I'll fix the conflict myself if someone else hasn't by the time we're ready to merge this.

**Comment by Pinkbat5** [comment]
Should be good to merge now, just finished the [other PR.](https://github.com/impstation/imp-station-14/pull/384)

**Pull request merged**
