### PR TITLE
crushers fit in tank slots

### PR DESCRIPTION
**Pull request by Sha-Seng**
EDIT: pr only includes crushers now, no fire axes

because if you can put machine guns and spears on your back, these should fit there too

while working on it i realized that none of the crushers flashlight-on sprites work, but i'm not personally sure how to fix that since it's an equippable, holdable, AND wieldable item.  if you wanna try to fix that, dm me on discord (shaseng) and i can toss you the lit sprites i had before giving up on that.  outta scope for this pr

image

:cl:
- tweak: Crushers fit in your suit storage now (the tank slot!)

### CODE REVIEW

**Comment by mqole** [comment]
thinking about this, i think this pr will contribute to the trend of vigilante salvagers - if theyre carrying around a big axe on green alert and sec yells at them, now they can just stow them instead of having to do the walk of shame back to their department, which personally i am not a fan of at all. if we had less of a selfsec problem on the server i'd be more open to this PR, and maybe its an idea that can be revisited in the future, but honestly i think this will just encourage salvagers to play like security 2 as is.

**Comment by mqole** [comment]
> i'd also argue that selfsec is an ooc issue and we should be correcting that with admin stuff rather than game design. cut people's hands off

speaking from an admin perspective here. it is 100x more exhausting to have a game with mechanics that do not support the server rules than a game where the mechanics actively work against the server rules. i dont like having to cut peoples hands off. id rather not have to do it in the first place.

salvagers should not be walking around the station on green alert with big fuckoff axes. it doesnt make sense from a roleplay perspective and, as someone who has also played security, its discouraging to see. why should i need to worry about doing my job if a salvager can just swoop in and 2-hit the spider i'm trying to stun? i understand that this sort of thing is difficult to regulate for security players, but we should be developing gameplay changes that make that task _easier_, not harder.

i want to see more salvagers lining up in security to get a firearm license so they can take their glaive to the bar.

**Comment by Pinkbat5** [comment]
Mechanical solutions to these problems ARE very valuable, but if the problem already exists right now, not adding this won't help-- it's clear that the inconvenience of needing to hold the weapon at all times is not stopping a lot of people. We need a real way to ensure that people don't run around with them. We shouldn't have to hesitate to add simple QoL features because the server culture surrounding salvage is that bad.
(Also: you can still make them do the walk of shame! We can have "don't open carry weapons around" policies as sec. Sure, it might be on their back, but it's still _out_.)

**Comment by Pivotbash** [comment]
Personally, I don't see much difference between a salvager wearing their crusher on their back or holding it in their hands. They're giving up having a large back tank to wear one, and will have geared up by that point to have an extended emergency tank to allow it. If a salvager wants to have their crusher on their person, they're going to carry it one way or another. 

Plus, salvagers can wear enforcers on their back, which are by-and-large significantly better weapons, and if a salvager can take out a player controlled dragon with a crusher, I'd say they've earned it.

As it stands, I don't think this pr adds to or takes away from anything relating to the security vs salvage debate, and is simply some quality of life that every salvage player would enjoy, and we shouldn't deny them that.

**Comment by mqole** [comment]
to be clear, im not necessarily against salvagers having some qol features, i just dont think this is the way to go about implementing them. i mentioned it in my first comment but i would love to revisist this pr **in the future,** once we've been able to discuss and implement a more robust solution to salvager vigilantism. maybe a finalised iteration of this will allow salvagers to straight up carry axes on their backs. maybe the qm will have access to a back-harness that can hold weapons. maybe the axe can fold up into a small, portable version with a long doafter, i dunno. for the time being though, i dont want to merge this pr until there's been some more discussion and/or balance changes.

(no salvager is gonna be using a fireaxe though so i will say that i think that thing should not fit in a back slot lol)

**Comment by mqole** [comment]
greatwrench would be funny and its a less common item that does less damage, so i have no complaints with it. im 90% sure sledgehammer is admin only though?

**Comment by mqole** [comment]
yeah thats what im saying, go for it with those two lmao

**Comment by Pivotbash** [comment]
I can almost guarantee that when salvage goes out and performs some vigilantism on an antag, it's not with a crusher. Everyone with a hardsuit can already wear lethal weapons on their back, and i haven't seen any calls for a pr to remove that feature because it gives them too much power. 

This should be brought up to salvage players directly, but I'm certain all of them will be for the change. I'd also bring it up in security.

As for fireaxes, I'm more for keeping it out of back slots if only because it has a specific wall closet in the department it belongs in. That item has been in a really weird place since before impstation was even a thing. It used to be The tool engineering needed to space a room for atmos reasons, but was removed because it was the meta for nukies to steal it and space every room they entered. Now that it can't do that it's just the engineer self defense weapon that also works as a crowbar. 

If the axe could still remove hull plating, I'd keep it out of a back slot. Since it can't, I'm not entirely sure how I feel about it. I'm not for or against letting it go in a back slot.

**Comment by RosySaturniidae** [comment]
salvage is a unique role in that it is the only role, other than security, that starts with explicit weaponry. yes, other jobs do have weaponizable items in some form or another (like the atmos fire axe, or the chef's meat cleaver), but the PKA and survival knife are items that are meant to be used to cause harm to creatures. it is tied to their job, in the same way that the armory is tied to security's. 

when it comes to usage of those items outside their intended purpose of battling space creatures (i.e shooting vent creatures on station, or stabbing someone to death as an antag), in-character enforcement of both space law and common decency are the main ways of dealing with this. if someone is getting in the way of security doing their job effectively, then there are both roleplay and space-law-enforcement ways of getting them to stop. and even then, security doesn't confiscate the chef's knives because they defended themself from a vent slime. thus, the salvage items are not illegal to possess, and aren't illegal to use unless you are using them illegally (in which case security can and should come down on you).

the crusher weapons (or specifically the axe and glaive, since this isn't an issue with the dagger) aren't really different from this perspective. they're luxury job items in the same way that advanced welders or disabler SMGs are (not round-start, but easily obtained over the course of a shift). they are more powerful than the items they replace, yes, but reasonably so.

if the primary concern with making it easier to carry those items around is a rise in "vigilantism" from salvage, consider that this happens regardless of whether or not they possess a crusher weapon. the issue isn't the existence of specific items or mechanics, it's a fundamental part of salvage to have and use weapons. changing this would require reworking the sub-department entirely, or at least making it significantly less fun. meanwhile, adding this sort of quality-of-life change won't really change the issues present, in either direction.

when it comes to in character enforcement, there's two things i would like to point out. first, vandalism, disturbance, and failure to comply are all crimes you can charge someone with. they're two 1-xx and a 2-xx respectively, but they are certainly enforceable should they need to be. second, alert procedures DO say that security is allowed to open-carry lethals on blue or higher. the alert procedure guidelines that security follows are separate from the space law that other roles follow, and thus you can still enforce the aforementioned laws if applicable, but there is precedent for holding/carrying weapons on blue or higher.

additionally, part of the issue is the nomenclature of "open carry" vs "wielding" being potentially vague, and as it currently stands, you have to be actively _carrying_ the items in question, as opposed to just having them be visible. you don't necessarily have to be two-hands _wielding_ it, but salvagers are still forced to walk around with a lethal weapons in their hands (should they choose to have the item in the first place). by allowing them to sling it, it puts them on the same level as anyone else with a long gun. 

finally, i'm not sure the utility of this for the job needs to be discussed. it's a quality of life change that allows salvage to do their job more efficiently, simple as. with how salvage functions after emogarbage smothered their hands on it, i doubt anyone is opposed to making salvage's job slightly easier in this way. (which is to say, the opposition is based on other contexts)

i don't play engineering enough to have an opinion on the fire axe. i feel that most of what i've said applies to it as well, though.

**Comment by lobsterpaw** [comment]
> an interesting point also arose in the security thread discussion about this: if we do, in fact, make salvagers store their weapons in their departments in situations where there's no apparent mortal peril, then being able to sling crushers on your back is arguably _even better_ for security because then you have a big fuckoff axe you visibly own and they know they need to talk to you
> 
> i still think we need to keep in mind that salvagers tend to have two _other_ ways to crit you in their bags, just from playing their job and carrying their things even if they're not doing anything illegal with them - and security can't even tell those are there unless we start doing random searches when there's another, greater threat to the station that needs our attention. and since crushers _very visibly_ fitting into tank slots, rather than being concealed in a bag, i really don't think it's going to change anything _besides_ making salvage players happier by letting them work with two hands without having to set their iconic item down on the floor

i made a github account so i can say that i think this is good logic. i'd rather be able to conceal or stash my murder weapon easily if i'm gonna murder someone as a salvager. i'd always go with a crusher dagger, knife, or derelict gun over a crusher, and those fit in bags.

**Comment by Pinkbat5** [comment]
I think it's worth pointing out that crushers not having any sling-ability is so inconvenient that I just straight up never use them. Not on expeditions, not on anything. All of its core features are present in more portable items so I just use those items instead.
And that sucks. Crushers should be viable for their original intended purpose, not for holding when you're on break. It feels like I only see them IN the bar because when you actually need to do salvage work, they just aren't the practical choice.

**Comment by Darkmajia** [comment]
crushers on back sure, fireaxe should probably stay in the cabinet. it has a home. also nobodys gonna be able to find the dang thing when its needed because an atmos tech is gonna carry it around all shift for the swag. i think strong beautiful salvager women should be able to carry big deadly weapons on their backs and im not biased

**Comment by mqole** [comment]
i still fundamentally dislike the idea of merging this pr as-is because of the grievances i mentioned, but its a fair point that crushers arent the _only_ things enabling salvage vigilantism. i'll maintain that while i do like this as a qol pr, i dont like this as a balance change that uplifts salvage (popular department) at the detriment of security (understaffed department).
> first, vandalism, disturbance, and failure to comply are all crimes you can charge someone with. they're two 1-xx and a 2-xx respectively, but they are certainly enforceable should they need to be.

please see:
> yes i could arrest them, but as stony has said, trying to impose too much order on salvage is exhausting and sisyphean to the point that they've stopped even attempting it because it's not fun for sec or salv

ig enough people have complained about it that saying any more here feels counterproductive. whatever, this can be merged. but if i start seeing salvagers taking their axes to the bar on green alert with security not at the very least ASKING them about it im gonna be real disappointed

**Comment by Darkmajia** [comment]
i did want to hold out on commenting on this pr until i implemented pressure scaling for the pka and crusher tag hits, but figuring out this code is hard.. ideally these weapons should be kinda sucks on-station and fully functional during the actual job, which makes carrying the weapons less of an issue. i'd still like to see security follow up on big fucking weapon being carried around on green though

**Review by Darkmajia — APPROVED** [review]
i will tentatively merge this for now and if it causes issues we can slam the revert button so hard

**Pull request merged**
