### PR TITLE
Reagent Migration

### PR DESCRIPTION
**Pull request by KingMudkipIII**
Reorganizes the filestructure of the reagents folder to fit new guidelines. Im mostly responsible for making this the nightmare that it is so I figured its my job to fix it.
**Changelog**

### CODE REVIEW

**Comment by DinnerCalzone** [comment]
I think these changes should be reorganized to go in the _Impstation folders that already exist higher up in the file structure to be consistent with how the other migrations have been done. For example `Resources/Locale/en-US/reagents/meta/Impstation/fun.ftl` should be `Resources/Locale/en-US/_Impstation/reagents/meta/fun.ftl`

**Comment by formlessnameless** [comment]
Yeah, please move this into the existing structure format. Thank you!

**Comment by KingMudkipIII** [comment]
someones messed with the files for subjuzine in the time its taken for me to do this. Im going to need help resolving the merge conflict

**Review by formlessnameless — APPROVED** [review]

**Comment by Cygnall** [comment]
Hey, checking on this - We recently ported genderfluid and noticed the sprite for it contains no copyright? Does anyone know who made this?

**Comment by kipdotnet** [comment]
> Hey, checking on this - We recently ported genderfluid and noticed the sprite for it contains no copyright? Does anyone know who made this?

Hive's gotten back to us, the sprites should have been attributed to Aftrlite (Github).

**Pull request merged**
