### PR TITLE
Listening Post

### PR DESCRIPTION
**Pull request by AirFryerBuyOneGetOneFree**
The listening post is coming soon....

Content Client_2CPIQPJIg2

:cl: Flanburgr, AirFryerBuyOneGetOneFree
- add: Added the Syndicate Listening Outpost, whose mission is to spy on the station and aid syndicate agents.

### CODE REVIEW

**Comment by formlessnameless** [comment]
Looks like the robust update messed up the versions here, pull from the main Imp branch and it should resolve it

**Comment by formlessnameless** [comment]
There's a couple of things that need fixing to make this work with the new mindrole stuff from upstream but there's a lot to explain, so I will merge this in tomorrow, test it and fix it myself.

**Comment by formlessnameless** [comment]
alright doing this now

**Review by formlessnameless — APPROVED** [review]

**Comment by FluffMe** [comment]
@formlessnameless Hi there!

Harmony is experimenting with the porting of the delta-v's listening post.
Imp Station had the most concise and recent port that included the mind roles and all that stuff.

Hope you don't mind us just ripping all of that out into a branch, and as far as licensing is concerned, we are also AGPL.

Please let me know if there are any issues with us grabbing this!

Thank you, this is an amazing work <3

**Comment by formlessnameless** [comment]
> @formlessnameless Hi there!
> 
> Harmony is experimenting with the porting of the delta-v's listening post. Imp Station had the most concise and recent port that included the mind roles and all that stuff.
> 
> Hope you don't mind us just ripping all of that out into a branch, and as far as licensing is concerned, we are also AGPL.
> 
> Please let me know if there are any issues with us grabbing this!
> 
> Thank you, this is an amazing work <3

Of course! You're absolutely welcome to it. The one thing to watch out for is that our rendition of the listening post map is custom, so there might be some things missing from your fork if that's the version you decide to use.

**Comment by FluffMe** [comment]
Already found the plushies and made it loadable! Our mappers will probably go ham on it and make their own outpost too.

Thank you and everyone involved very much!

**Pull request merged**
