### PR TITLE
new cute folders for the loadout

### PR DESCRIPTION
**Pull request by Darkmajia**
new cute folders that are only obtainable through the trinkets loadout, replacing the regular black folder. they have 2 regular paper and 1 office paper guaranteed, rather than relying on random spawns like the other folders do. thank you carousel for the sprites!!!!!!!!

dont look at the commit. i forgot putting exclamation marks in git bash does that

**Changelog**
:cl:
- add: New folders are available in the trinkets loadout with consistent paper and cute themes!
- remove: The black folder is no longer in the trinkets loadout. Pick a new one out!

### CODE REVIEW

**Comment by Pinkbat5** [comment]
These are absolutely lovely, but can we keep the black folder too?

**Comment by Darkmajia** [comment]
i don't really want to make an item that looks the exact same as the existing black folder but has veeeery slightly different functionality in terms of consistent paper spawns. i guess there's no real harm in it, but it just feels strange to me. i'll think on it, nobody merge this pr yet pleasies

**Comment by Pinkbat5** [comment]
Maybe we could have a black variant with a stripe or other small change to its design? It doesn't need to look identical to the default folder, I just like the versatility of a more formal, plain black.

**Comment by widgetbeck** [comment]
> i don't really want to make an item that looks the exact same as the existing black folder but has veeeery slightly different functionality in terms of consistent paper spawns. 

You could just have something along the lines of;

`
- type: entity
  id: BoxFolderBlackTrinket
  parent: [ BoxFolderBase, BoxFolderBlack ]
  components:
  - type: StorageFill
    contents:
    - id: Paper
    - id: Paper
    - id: PaperOffice
`
This avoids duplicating the whole proto.

**Comment by Darkmajia** [comment]
i was mostly concerned about having an item that looks identical with slightly different function in terms of like, clarity? but it's a reallllllly minor thing. i also totally forgot about this pr, whoops

**Comment by widgetbeck** [comment]
yeah, that's what the suffix is for. it's not functionally important for the player to know, but it'd have the suffix [Trinket] in the f5 spawn menu

**Comment by Darkmajia** [comment]
i changed the black folder slightly and added the loadout suffix so it's clear to mappers that these folders have slightly different functionality. it's minor, but it's a difference

**Review by widgetbeck — APPROVED** [review]
thumps up

**Pull request merged**
