### PR TITLE
Thaven mood changes.

### PR DESCRIPTION
**Pull request by widgetbeck**
Added conflict between "Only Speak To Command" and "Most Important Person," because they overlap too much. Typing quirk moods will no longer roll while I retool them. Also added a 10% chance for the "folk hero" EMAG mood to be replaced with Die A Glorious Death. 

**Changelog**

:cl:
- tweak: Changed

### CODE REVIEW

**Comment by formlessnameless** [comment]
I'm worried that people might see the name of the DAGD mood and take it to mean that they have carte blanche to explode the station however they like. The game isn't telling you you're an antag when the mood changes, but I could see misunderstandings happening. Maybe we could add some clarification in the species guide about it?

**Comment by widgetbeck** [comment]
it was kind of the intent in having it be extremely rare (the chance of
rolling it on emag is <1%, and emagging doesn't happen every round) that it
be an excuse to self-antag. I can change the text of it to be more
restrictive if you think it's too much to have as a species feature. Like,
"Die in an interesting way. Try not to take anyone else out in the process."

**Comment by hivehum** [comment]
i liek the rewording of that but its also not framed like any other thaven mood is. would be better to be something like. idk. 

"You desire to die in a glorious way, a brilliant light snuffed out in its brightest moment. But you are not a murderer."

**Comment by widgetbeck** [comment]
gimme a few minutes, I'll change the wording rq

**Review by formlessnameless — APPROVED** [review]

**Pull request merged**
