### PR TITLE
Language.

### PR DESCRIPTION
**Pull request by honeyed-lemons**
Added the entire language system from Einstein Engine. We don't have the language menu on character creation because it couldn't be ported over super easily
:cl:
- add: Language System with so many languages, including gray
- add: Foreigner Trait that makes it so you don't spawn with common
- add: Multiple levels of translator research

### CODE REVIEW

**Comment by formlessnameless** [comment]
Honestly having the language menu on character creation feels like a big part of this, but I'm not super familiar with the system. It sounds like you just don't get to pick what languages your character knows at the start then with how this currently is?

**Comment by honeyed-lemons** [comment]
It's a big part however the system from Einstein is not portable currently, It'd require a custom menu I do not know how to create. Currently languages are determined by your species

**Comment by honeyed-lemons** [comment]
If someone who is familiar with menus wants to take a crack at it, I'm all for it

**Comment by hivehum** [comment]
i think this is really sick and i respect the amount of work you put into porting it but im honestly not sure how i feel about it as part of our fork, especially porting grayspeak into the system. grayspeak is The defining trait of grays (particularly in comparison to our other custom species) and i think its mechanically really important that it is something that can be learned and understood through game knowledge. if grayspeak is implemented like my understanding of EE's language system then it becomes random words to anyone not fluent which is... significantly more boring imo

languages are requested frequently and i think it has a lot of potential but ultimately im not sure this particular implementation is it

**Comment by honeyed-lemons** [comment]
That's fair, we can remove grayspeak from it if you'd like, I wasn't incredibly happy about it either

**Comment by Darkmajia** [comment]
grayspeak as a pure accent, as it is now, would be fun and fine. makes you wonder how the grays even developed their language. i really would love to talk to vent slimes as a slimeperson

**Comment by formlessnameless** [comment]
sounds like there are some changes pending from discord discussion, going to put this off until after the upstream merge for now

**Review by formlessnameless — APPROVED** [review]

**Pull request merged**
