### PR TITLE
(do not merge) Add janitorial techfab, lathe recipes for soap and cleanades

### PR DESCRIPTION
**Pull request by DinnerCalzone**
Adds a janitorial techfab to the game, which can be used to produce janitorial supplies. The machine board for it is available from the circuit imprinter at round start, costing 1 steel and 5 glass like most other machine boards. Almost all of the items produced by the janitorial techfab can already be produced from an autolathe or protolathe, this addition would primarily be adding a new source of production for these items without needing science to hand off an autolathe machine board. 

However, there are two items that would be exclusive to this lathe: mop buckets and soap. The mop bucket recipe was already in the game, but seemingly unused, costs 1 steel 1 plastic. Soap is a lathe recipe unique to the janitorial techfab, costing 2 plastic and 2 plasma (inspired by the description of the NT soap). Another new lathe recipe also added is cleanades, which requires the Tier 2 Advanced Cleaning technology to craft, can be produced at both the protolathe and janitorial techfab, and costs 4 steel, 2 plastic, 1 glass, and 1 plasma to craft.

list

Content Client_sOlU8nVURe

Content Client_NbhHs6i3DU

Content Client_gp5pN7FBgo

Content Client_rUM9wI6Vjz

**Changelog**
:cl:
- add: Added the janitorial techfab, which can be used to print off a number of useful janitorial supplies, including mop buckets and soap! The machine board for it can be printed from the circuit imprinter in science.
- add: Cleanades can now be crafted from protolathes and janitorial techfabs after researching Advanced Cleaning.

### CODE REVIEW

**Comment by theqwat** [comment]
i will note this has an equivalent in 13 that is the service lathe which is shared between that department... could maybe be a good idea to add bartender things and botany things to it, otherwise i can say this is overall a positive..... though i will say isnt there a chem recipe for soap already? and assuming that line of text "contains no chemical" i must ask from an outsider perspective "can you make recipes require chems" for the clean nades atleast

**Comment by DinnerCalzone** [comment]
The 'contains no chemical' line refers to the fact that you can load lathes with space lube or glue to either speed up or slow production process. I don't believe you can have a lathe recipe use chemicals. The closest there is to something "chemically" is plasma, which fits with the description of the NanoTrasen soap.

**Comment by Darkmajia** [comment]
i think a general service lathe like its equivalent in 13 would be a little more ideal, the other non-basic lathes are departmental rather than for a specific job. buckets in this are already useful for botany but you could also add botanical tools, metamorphic glasses, skewers, bowls, etc

**Comment by DinnerCalzone** [comment]
I suppose I could expand the functionality to be a service techfab. The thought did cross my mind since there's already sprite assets for a service techfab in the game. What steered me more toward restricting it to being janitor focused though was that not all maps have areas that are restricted by general service access, so they would likely end up in more public areas. I also really like purple...

**Comment by Darkmajia** [comment]
i love purple too and i do think finding space for it can be difficult, but honestly if it was just put behind the bar which is kind of a "commons" area for service or put in a service-locked door in maintenance near the bar/kitchen/botany, especially for mappers, i think itd work okay. a janitor could just ask for a service lathe and put it in their own room anyway, especially since theyll likely have the most use for it

**Comment by DinnerCalzone** [comment]
Do you think I should use the service techfab sprite that's already in the game, which is a sir holding a serving plate on a light green background?

service

**Comment by Darkmajia** [comment]
it does kinda look like a toilet. i enjoy its sir-like qualities but its up to you

**Pull request closed without merging**
