### PR TITLE
expansion for french and russian accents

### PR DESCRIPTION
**Pull request by KingMudkipIII**
**Changelog**

:cl:
- add: Added a boatload of new words to the french and russian accent systems.

### CODE REVIEW

**Comment by Pinkbat5** [comment]
I love most of this, but there's a few word replacements I'm not crazy about. These accents originally focused on replacing letters, nouns (captain, doctor, grandma, etc) and common phrases, but replacing words like "my", "run" or "help" seems too extreme. It's going to be too confusing and not flow as well in conversation, IMO.
A few of the noun replacements might be too extreme too, like "katushka tesly" instead of tesla coil-- to the average english speaking monoglot it's going to be hard to guess what "katushka" means. Do we want the russian accent to cause grey-adjacent guessing games like this? idk. Just my 2 cents. This opinion does not extend to the french accent because I think it's funny

Also, two bugs I found: "space station" is translating to "space stantsiya", not kosmicheskaya stantsiya as intended. And "doc" is translating to "doktor" instead of "dok"

**Comment by KingMudkipIII** [comment]
I still have the original files, so I can cut them down to more basics, and flesh them out more later if its needed! gimme a bit and ill do a revision

**Comment by KingMudkipIII** [comment]
commented out a bunch of the russian. Ill see if I can get a basic french and russian as selectable too? Not quite sure how it works

**Comment by KingMudkipIII** [comment]
Im currently unable to get an extra set of accents working. Ill leave this prq up, but ill probably need help adding that if its going to be a requirement for merging

**Comment by KingMudkipIII** [comment]
Got it working! Theres russian (basic) and french (basic) now. They work as the current live accents do, minus french basic having yes and no still replaced since I think thats fine.
image

**Comment by hivehum** [comment]
this is a little bit out of the scope of this pr but like. for the record. the Cyrillic letter swap form of the russian accent is a complete accessibility nightmare for people that use screen readers

**Comment by KingMudkipIII** [comment]
I *can* remove it, if needed?

**Comment by hivehum** [comment]
idk if its needed. just kind of a general complaint on my part. i'm blind and don't currently use a screen reader but have in the past so i was honestly taken off guard that a game was willing to do something as blatantly inaccessible as the basic russian accent to begin with

**Comment by KingMudkipIII** [comment]
Ill call it out of scope for this one, but definitely raise it as a git issue just to get discussion. Im not blind but I do still have trouble reading it lol

**Comment by KingMudkipIII** [comment]
Requesting a review on this, it should be good to go

**Review by formlessnameless — APPROVED** [review]

**Pull request merged**
