### PR TITLE
slime water + water vapor, gastropoid salt damage adjustments

### PR DESCRIPTION
**Pull request by Darkmajia**
slime water damage is so fucking insanely overtuned and seemingly untested. there was a code comment about slimes being killed in 7 water pistol shots: it only takes 5. compared to upstream, this pr gives slimes double the water weakness, and retains the caustic damage instead of upstream's heat damage, which makes it more punishing since it can't be naturally regenerated. water vapor damage values have been adjusted to match https://github.com/space-wizards/space-station-14/pull/32751, using caustic damage instead of heat

also adjusted gastropoid's weakness to salt and salt-based reagents to fall more in line with slimepeople's water weakness. did you know a single 10u spray of readily-available table salt does 80 heat damage to snails currently? i did.

**Changelog**
:cl:
- tweak: Slimepeople have had their weakness to water and water vapor reduced.
- tweak: Gastropoids have had their weakness to salt and salt-based reagents reduced.

### CODE REVIEW

**Comment by hivehum** [comment]
do you want to pare this down to just nerfing damage to snails or should i close this

**Comment by Darkmajia** [comment]
i would like to keep this open because people are still going to complain about water vapor damage and fire extinguishers over the next 24 hours. i'll resolve conflicts afterwards. or i can eat my words instead, really depends

**Comment by DinnerCalzone** [comment]
I made my adjustments in a rush before going to bed just so we would have a PR in place to address it ASAP and I don't think I went far enough tbh. I think the numbers in this pr could stand to be a smidgen higher (.5 damage per u of water at most), but I don't think a bucket of water should have comparable damage to the captain's saber with a harder to heal damage type. If people want to eviscerate people with fire extinguishers, they should also have to go through the effort of filling them with razorium

**Comment by Darkmajia** [comment]
yeah i noticed that too

**Review by formlessnameless — APPROVED** [review]

**Comment by kipdotnet** [comment]
Im more shocked that its taken this long, I was under the impression everyone knew how crazy salt was? Worth noting that gastropoids have a 20% vulnerability to poison so it was actually more than 80. Two syringes of saline and a medipen makes a gastropoid unrevivable without necrosol iirc

**Pull request merged**
