### PR TITLE
Supermatter Engine Port

### PR DESCRIPTION
**Pull request by honeyed-lemons**
Ports the Supermatter from Einstein Engines ([#341](https://github.com/Simple-Station/Einstein-Engines/pull/341)), radiation shielding adjustments ([#791](https://github.com/Simple-Station/Einstein-Engines/pull/791)) and prevents radiation damage from stopping doafters ([#606](https://github.com/Simple-Station/Einstein-Engines/pull/606))

**Changelog**
:cl:
- add: added the Supermatter Engine
- tweak: Radiation shielding adjustments.
- tweak: Radiation no longer prevents doafters

### CODE REVIEW

**Comment by Darkmajia** [comment]
searching for "supermatter" on ee prs, it might be worth looking into https://github.com/Simple-Station/Einstein-Engines/pull/791 as well, but i would loooooove to have this. ideally on as many maps as possible, but to start off with, maybe just one common map in place of the teg to ease people into it? like bagel? as for cargo ordering, there doesn't seem to be any additional infrastructure that cargo _could_ order: this is just the supermatter crystal, there's no supermatter shard which is the typical cargo order. the rest of a supermatter engine is just radiation collectors and emitters

**Comment by honeyed-lemons** [comment]
I saw that pr after looking it up! Also I agree about the map thing. How about we implement it into box? As it’s my map to maintain.

**Comment by Darkmajia** [comment]
that sounds good too. you could look at [beestation's version of box](https://affectedarc07.github.io/SS13WebMap/BeeStation/BoxStation/) to see how it's set up on there, although it doesn't seem like this pr comes with emitter reflecters which changes a few things. radiators are also different over there, too

**Comment by mqole** [comment]
i need her so bad

**Comment by formlessnameless** [comment]
yeah if it's from EE i'm down for it. The SM is cool

**Review by Darkmajia — APPROVED** [review]
im satisfied with my testing. supermatter real (once it gets mapped)

**Pull request merged**
