### PR TITLE
Crayons are now infinite

### PR DESCRIPTION
**Pull request by TGRCdev**
**Changelog**

:cl:
- tweak: All crayons are now infinite. Go forth and produce art.

### CODE REVIEW

**Comment by iaada** [comment]
I don't really like removing another reason for cargo to exist, crayons are super cheap. It's far more impressive when someone does something within restrictions and by coordinating help from multiple different people (cargo). If cargo is broke, it's not hard to find 500 spesos of garbage to trade for your crayons.

**Comment by theqwat** [comment]
i can agree that it should be increased but infinity is maybe to much.... 100 or even 50

**Comment by iaada** [comment]
I feel the pain point with crayons is running out of the color you want to use. An implementation that doesn't increase the count, but allows for better color selection would go over better for me. IMO, you should increase the size of the crayon box and add a rainbow crayon or two to the fill.

**Comment by TGRCdev** [comment]
Maybe each non-rainbow crayon has a set of shades that it can pick from for its respective color? Like, lightly shading vs heavy shading?

**Pull request closed without merging**
