### PR TITLE
[EE port] the throwing update

### PR DESCRIPTION
**Pull request by Darkmajia**
ports the throwing update (https://github.com/Simple-Station/Einstein-Engines/pull/1307) from einstein engines, along with some system refinement and implementation on our own content

this pr also changes existing `_EinsteinEngine` folders and mentions to `_EinsteinEngines` and includes a better implementation of pacifist throwing: pacifists can throw items that deal throwing damage, but those items will not actually collide with other players. items that damage on landing (such as metamorphic glasses) still cannot be thrown. also also, a few items have been turned into melee weapons. these should be generally acceptable, i hope

the following section is copied from the technical details of the original pr, so developers have an easy resource for adding these components to their own content:
## Technical Details
To make a melee weapon also a throwing weapon, just add `- type: DamageOtherOnHit`, and it will automatically inherit the damage from a light melee attack and the melee sound effect as the thrown hit sound effect. You can set a custom damage value with the `damage` field (necessary when the item is not a `MeleeWeapon`) and stamina cost with `staminaCost`.

To make the throwing weapon embed and deal damage over time when embedded, add `- type: EmbeddableProjectile` and `- type: EmbedPassiveDamage`. By default, the embed damage per second is 5% of the throwing damage, but it can be modified on `EmbedPassiveDamage` with `throwingDamageMultiplier`.

The default stamina cost for throwing is 3.5 stamina. The baseline cost for almost all DoT embeddables is 5 stamina, because of the extra damage the DoT brings.

[2024-12-29 22-38-50.webm](https://github.com/user-attachments/assets/931488b3-5cfc-4623-a3bc-49df985d0bd2)

**Changelog**
:cl:
- add: A few items can now be used as melee weapons.
- add: Pacifists can now throw most dangerous items, but still cannot cause harm with them.
- add: Ported the Throwing Update from Einstein Engines, which includes:
- add: Many items can now be thrown to deal damage.
- add: Examining an item will show a lot of information about its throwing potential.
- tweak: Items that deal throwing damage now cost stamina to throw.
- tweak: The default time to remove an embedded item has been increased from 3 seconds to 5 seconds.
- tweak: The time to pry up a floor tile has been reduced from 1 second to 0.5 seconds. Throwing tiles deals more damage.

### CODE REVIEW

**Review by TGRCdev — APPROVED** [review]
Finally I can bean tools at my fellow engineers' heads

**Comment by Darkmajia** [comment]
man fuck my life. i gotta merge beg more so i dont have to fix anything ever

**Comment by TGRCdev** [comment]
I got it dw

**Comment by Darkmajia** [comment]
man love my life. love people do my work for me. thank you my hero

**Pull request merged**
