### PR TITLE
Pulled lockers/crates can now only be opened by the person pulling them

### PR DESCRIPTION
**Pull request by TGRCdev**
Fixes a long standing issue of pulling material crates / lockers / dumpsters and random dipshits clicking on them and spilling the contents.

**Changelog**

:cl: TGRCDev
- tweak: Crates/lockers being pulled can now only be opened by the person pulling them

### CODE REVIEW

**Comment by hivehum** [comment]
i kinda dont feel like this is an issue/bug, personally. there are plenty of valid reasons you would want to open a crate or locker that someone else is running away with or otherwise making it difficult for you to intercept the pull

**Comment by TGRCdev** [comment]
If you really wanted to stop someone and search their stuff, you could just CTRL+Click the container and then click to open. It's not a huge barrier to actually searching someone, just a prevention for Joe Passenger opening an engineer's mat crate and spilling their Plasteel.

**Comment by Darkmajia** [comment]
i dont think its that big of a problem and this creates a very weird mechanical barrier. if i press e on an unlocked, unwelded crate it should really open no matter what

**Comment by hivehum** [comment]
also personally ive been in situations where someone trapped and locked me in a locker while i was typing and ran away with me and i would have become the joker if other people couldnt let me out

**Comment by TGRCdev** [comment]
> i dont think its that big of a problem and this creates a very weird mechanical barrier. if i press e on an unlocked, unwelded crate it should really open no matter what

This doesn't affect 99% of other crate-related situations. Pressing E will still open a crate if it is not locked and it is not welded. It's not unreasonable to say that you can't open a crate if someone is actively holding it.

> also personally ive been in situations where someone trapped and locked me in a locker while i was typing and ran away with me and i would have become the joker if other people couldnt let me out

If the locker isn't welded or locked, all you would need to do is CTRL+Click to take the locker from the other person, and then E/Click to open it. If the locker is locked/welded, then other people wouldn't be able to open it anyways!

**Comment by TGRCdev** [comment]
Also, if you aren't restrained, you can still exit a crate/locker being pulled by someone else.

**Review by formlessnameless — APPROVED** [review]

**Pull request merged**
