### PR TITLE
Make Sir Gollylad less likely to get trapped in maints. Also Gobtools

### PR DESCRIPTION
**Pull request by widgetbeck**
**Changelog**

:cl:
- tweak: Sir Gollylad will now spawn with a passenger ID card, so he can escape maints more easily. Also a gobtools crowbar.
- add: Goblin Stowaways' tools (gobtools) now have unique sprites.
- tweak: Goblin Stowaways should be less common, and can only be triggered once.

### CODE REVIEW

**Comment by hivehum** [comment]
i feeeeel like it might be better to make his sword a jaws of life and then dont have him spawn with an ID. plenty of more antagonistic ghost roles have the ability to pry doors so i dont think thats a huge balance chance imo

**Comment by kipdotnet** [comment]
if youre going to do the jaws route, you should change the success sound to be the sound the holy sound the bible makes when it heals someone. gesus compells the door to open

**Comment by widgetbeck** [comment]
he's not an antag, hes a familiar

**Comment by kipdotnet** [comment]
I think hive was saying that theres antags who are a much more direct threat to the station who can pry powered doors, so giving it to a very limited, rare familiar is really honestly not that big of a deal

**Comment by kipdotnet** [comment]
also I adore the tools sprites btw. theyre so good and I think I forgot to say that when you first showed them off

**Comment by Darkmajia** [comment]
i don't think there's anything about the sword that communicates it could be used as a crowbar or, pushing it even further, a jaws of life. part of the random nature of the game is that sometimes you are, especially as a ghost role, fucking stuck and need help. shouting and screaming might not be that fun but closet skeletons have needed to do this forever. i know skeletons are free agents and incredibly likely to start tearing shit up as soon as they get out, but this feels like it's overcompensating for a ghost role that has barely had time to exist on the server yet

**Comment by hivehum** [comment]
i would counter regarding the sword that i think it plays into the identity of goblins to use an item like a bladed weapon in an inappropriate way (wedging it into a door to pry it open). its charming and funny

**Comment by widgetbeck** [comment]
> i don't think there's anything about the sword that communicates it could be used as a crowbar or, pushing it even further, a jaws of life. 

it's a metal stick. goblin's gonna use a metal stick to pry open doors. i don't think it should be a jaws of life, but it being a crowbar both is in-theme with the character and doesn't provide substantial gameplay benefit - it'd only be useful for opening doors when the power's out, and you can get a crowbar basically anywhere for free anyway.

skeletons having to bust their way out of maints is fun and interesting because that's part of the point of the role, whereas Sir Gollylad is an almost purely RP ghostrole, so allowing him to get out of (some of) the situations in which he might spawn by himself just lets players get to the roleplay bit faster

**Comment by Darkmajia** [comment]
> i would counter regarding the sword that i think it plays into the identity of goblins to use an item like a bladed weapon in an inappropriate way (wedging it into a door to pry it open). its charming and funny

this item isn't explicit to sir gollylad, though. anyone can pick up the "sword that's also a crowbar for some reason" and just use it. there's nothing about the item that communicates this intent

> it's a metal stick. goblin's gonna use a metal stick to pry open doors. i don't think it should be a jaws of life, but it being a crowbar both is in-theme with the character and doesn't provide substantial gameplay benefit - it'd only be useful for opening doors when the power's out, and you can get a crowbar basically anywhere for free anyway.

there are a lot of metal sticks in the game that don't pry open doors. if we've denied flash protection on huds for lacking the visual information to communicate it, i don't see why the new funny ghost role's toy should be exempt. if you can get a crowbar anywhere for free, why would it be a problem for sir gollylad to go get one?

> skeletons having to bust their way out of maints is fun and interesting because that's part of the point of the role, whereas Sir Gollylad is an almost purely RP ghostrole, so allowing him to get out of (some of) the situations in which he might spawn by himself just lets players get to the roleplay bit faster

i take issue with this. i think it's incredibly uninteresting to just be given everything you need to skip the initial steps of being given a bad spawn in the name of getting to "the good stuff". being stuck in maintenance can _be_ the good stuff. the crowbar aspect is unclearly communicated, kind of unnecessary, and will only be noticed by people paying attention to the github/changelog at the exact time it goes through. the passenger id skips an essential inducting process into the crew if sir gollylad or his charge even want to go through with that, and requires silicons to regard him as crew. this feels like it's trying to propel the new, shiny ghost role into a spotlight rather than keeping it in line with other existing items and ghost roles

**Comment by widgetbeck** [comment]
Dark, are you aware that the sword does *less damage* than a crowbar?

**Comment by Darkmajia** [comment]
i don't see what that has to do with anything i said?

**Comment by widgetbeck** [comment]
you seemed to be concerned with "anyone being able to pick it up and use it" 
i still don't really see any issue with either of the changes - my intent was never for him to be inline with closet skeletons or antag ghost roles, it was for him to be like Pun Pun, a reoccurring named character, but rare, and with a clear goal. he's on the station because he was assigned to protect a member of the crew, so he has a passenger ID because he's a passenger. the sword is a crowbar in case the area he spawns in is spaced. 
edit the PR before merging if you think it's that big an issue, but I really don't see it.

**Comment by Darkmajia** [comment]
my concern with anyone picking up the sword and using it as a crowbar isn't about it being a good or even reasonable option. it's that it doesn't communicate "goblins using the wrong object in funny ways" when it's not goblin-explicit. it is just an item that is a crowbar without anything really making that clear. if gollylad needs a crowbar to escape spacing, put a goblin crowbar in his backpack (or belt slot if it fits) rather than this weird, unclearly-communicated measure

**Comment by widgetbeck** [comment]
would it help if i put something in its description mentioning the
function? couched in more flavor than that, of course. Something like "Its
dull metal blade is thick enough to be used as a prying tool, and judging
from the dents in its surface, it has been."

**Comment by Darkmajia** [comment]
it would help, sure. i really feel like something that looks like a sword and acts like a sword should just be a sword, though, even if it is a crappy sword. if it wants to be a crowbar, it should look like a crowbar. this is my main contention

**Comment by widgetbeck** [comment]
i mean, it doesn't act like a sword. it does 5 blunt damage and the
description says it's a toy

**Comment by Darkmajia** [comment]
then i have to reiterate "if it wants to be a crowbar, it should look like a crowbar". i think the ideal solution to this problem is to give gollylad a crowbar when he spawns rather than turning his sword into a crowbar. i feel like the majority of players who pick gollylad up aren't even going to realise the item has this function

**Comment by Pinkbat5** [comment]
Would changing the description of the sword help communicate a crowbarring function? Because the mental image of a goblin using it like that is pretty fun.

**Comment by Darkmajia** [comment]
it would help, although it feels like it sidesteps my issue a bit. i'm not really the arbiter of whether this makes it in or not though, i'm just voicing my own concern. i don't disagree that it would be fun, it just feels strange to me

**Comment by Pinkbat5** [comment]
You raise a good point, though. I also like it when the function of items is immediately clear...
Maybe the sword could also be bent to more closely resemble a crowbar? Because it's funny?

**Comment by mirakurutaimu** [comment]
rather than tying it to the item, would it be possible to give him an innate ability to pry doors (like spiders do)?

**Comment by JLondon1** [comment]
> rather than tying it to the item, would it be possible to give him an innate ability to pry doors (like spiders do)?

This solution would let you use the dead body of Sir Gollylad as a jaws of life to open any door the spider's innate ability lets you open.

Ship it. Just imagine pickin that guy up by his legs and prying a door open.

**Comment by mqole** [comment]
there is some precedent for a weapon to function as a crowbar too. fireaxe already does it. its probably out of the scope of this pr but if there are concerns about clarity for gollylad's sword not being evident that it's a crowbar, i'd personally echo that sentiment about the fireaxe

**Comment by Darkmajia** [comment]
i feel like i might become the joker? a fireaxe is a tool moreso than a weapon, it just happens to get used as one in our space game about dying badly. firefighters are not bringing that thing to kill people. if a sword has ever been used as a reasonable breaching tool i would so love to see it

**Comment by Darkmajia** [comment]
i do realise things don't have to match their realistic function at all in silly space game, though. this has become more contentious than i imagined, so we can just merge it or whatever. i don't feel that strongly about one particular item, i just don't like giving things attributes that hardly make sense beyond streamlining one particular issue that could be resolved in a more elegant way

**Comment by widgetbeck** [comment]
i gave gollylad a goblin crowbar in his satchel pls merge now

**Review by hivehum — APPROVED** [review]
ideologically i don't think he should have a passenger id but you're asking me so niceys

**Pull request merged**
