### PR TITLE
medsec flash protection per 692 discussion

### PR DESCRIPTION
**Pull request by Sha-Seng**
if we merge this do it after https://github.com/impstation/imp-station-14/pull/692 and it should be fine

per the discussion on that pr this might actually be ok since we're making the recipe require existing flash protection from a relatively limited resource.  leaving the sec hud in the recipe too though so you still gotta run to the sec vendor (collection quests are good for you).  i don't even play brigmed so i'm just throwing this into the room like a grenade and leaving gl

:cl:
- tweak: MedSec Hud craft now requires security glasses instead of a radio
- tweak: MedSec Hud is now flashproof

### CODE REVIEW

**Comment by Pinkbat5** [comment]
Looks good! I have a suggestion: add a non-flashproof version that uses the [original, hudlike, non-pink sprite](https://github.com/space-wizards/space-station-14/tree/master/Resources/Textures/Clothing/Eyes/Hud/medsec.rsi) and the original recipe
I wonder how cool it would look if the glasses were made to look like 3D glasses, with a red and blue lens? Might be a little too goofy..

**Comment by Pivotbash** [comment]
I'm all for its addition, and I do think it's funny how they apparently became synonymous with brigmedic completely by accident.

So, people's concerns are that this would be too strong, and encourage brigmedics to try and go out to be combat experts that can see enemies exact health values on the fly and know when to push, or point out anyone closer to death than the others, and this is a valid concern. The thing with that though, there's nothing stopping a CMO from doing this anyways, or any other doctor with a medhud, sitting in the backline of a firefight, stealing a glance, and quickly pointing at anyone that's lower health, and is not unique to the medsecs.

Another concern I heard is that this would encourage them too much to go and be sec officer number 5, and shirk their duties to go and be a super cop. First off, there's nothing stopping a brigmedic from just putting on regular sec glasses and doing that, just the same as there's nothing stopping them from abandoning sec to just be another doctor when they're short on staff. The ability for brigmedic to serve both of these jobs is what makes it an interesting job to me. Having glasses that can serve both of these functions helps reinforce that, as well as enable the fantasy of being a combat medic on the front lines of a disaster. 

Brigmedic has suffered from being this kind of flex role though, as every other job has a clear, defined niche that they fit into. With the current implementation of brigmedic, I would define it as more of a flex slot, but still with the distinct of making sure officers and prisoners are taken care of. I would still deny brigmedic a firearm until red alert though, as to help reinforce them as more of a healer than a fighter. 

Overall, the major use these glasses would get is making it so other officers don't accidentally blind you by running past the portable flashers, and save a 1x2 slot in their inventory from not having to carry around two pairs of glasses.

**Comment by SnazzyGator** [comment]
I don't think flash protection is necessary, but it's not a big enough change to hurt anything and is very appreciated QoL, if not only to let brigmed players have their one special toy.

the concern about brigmeds playing as a backfill secoff has more to do with server climate and role meta, imo, and if the glasses having flash prot causes that big of an issue then I'd say the issue runs deeper than that. if staffing is so bad that brigmeds need to be doing arrests and such, then the problem is that not enough people are playing sec! it doesn't seem to me like most brigmed players are choosing the role to just be Secoff+, but end up feeling like they have to when the whole team of 4 is busy and a suspect open-carrying a gun walks right by them.

for my style of play personally, the medsec having flash protection would enable me to be a little more defensive than offensive, which I feel like is the idea for brigmed anyway. instead of engaging a target I could use a wide flash or flashbang and run away without having to fumble for my other pair of glasses in what might be a second before I get shot. it might even be a good idea to put a portable flasher in or near the brigmed bay to deter unruly brig patients when its THAT kind of shift.

all in all it just expands on player creativity and role flexibility and I think that's a good thing.

**Review by TGRCdev — APPROVED** [review]

**Comment by TGRCdev** [comment]
I'm okay with merging this for the sake of brigmed players. If it gets abused by sec we can work on further refining it.

**Pull request merged**
